### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by lilydujinyan** [missmess/vite-plugin-qiankun-x#1]
vite-plugin-qiankun-x  使用安装对node 或者vite版本有要求吗？安装使用后启动程序回报错
failed to load config from /Users/dujinyan/Desktop/work/kssec-fe/vite.config.ts
error when starting dev server:
Error: Cannot find module 'node:stream'

**Comment by missmess** [comment]
找到问题了，这是由于我引入了第三方包`cheerio@1.0.0`。而该三方包要求node版本在18.17以上（[package.json](https://github.com/cheeriojs/cheerio/blob/v1.0.0/package.json#L159)）。

我将依赖改为`cheerio@1.0.0-rc.12`。它不再需要如此高的node版本（[package.json](https://github.com/cheeriojs/cheerio/blob/v1.0.0-rc.12/package.json#L48)）。

将`vite-plugin-qiankun-x`更新到`0.3.0`即可。
